- name: install libqb / libqb-devel
  yum: name={{ item }} state=installed
  when: libqbsrc == 'system'
  with_items:
   - libqb
   - libqb-devel

- name: remove system libqb if installed
  yum: name={{ item }} state=absent
  when: libqbsrc != 'system'
  with_items:
   - libqb
   - libqb-devel

- name: libqb git clone
  git:
   repo: '{{ libqbgitrepo }}'
   dest: /srv/knetansible/src/libqb
   clone: yes
   force: yes
   version: '{{ libqbgitver }}'
  when: libqbsrc == 'git'

- name: libqb autotool
  shell: cd /srv/knetansible/src/libqb && ./autogen.sh
  when: libqbsrc == 'git'

- name: create /srv/knetansible/build/libqb
  file: path=/srv/knetansible/build/libqb state=directory mode=0755
  when: libqbsrc == 'git' or libqbsrc == 'local'

- name: setup build tree (from git)
  shell: cd /srv/knetansible/build/libqb && /srv/knetansible/src/libqb/configure {{ libqbconfopt }}
  when: libqbsrc == 'git'

- name: setup build tree (from local)
  shell: cd /srv/knetansible/build/libqb && '{{ libqblocalpath }}'/configure {{ libqbconfopt }}
  when: libqbsrc == 'local'

- name: build / install libqb
  shell: cd /srv/knetansible/build/libqb && make {{ libqbbuildopt }} all install && ldconfig -v
  when: libqbsrc == 'git' or libqbsrc == 'local'
