---
# top level playbook
# Install all build depedencies and keep hosts updated
# clone/build/install code
# run tests
#

- name: Install and build everything
  hosts: test-nodes

  roles:
    - hostsetup
    - libqb
    - kronosnet
    - corosync

- name: corosync tests
  hosts: test-nodes

  roles:
    - corosync-tests
    - kronosnet-tests
