- name: generate authkey
  shell: dd if=/dev/zero of=/etc/corosync/authkey bs=4096 count=1

- name: authkey permission
  file: path=/etc/corosync/authkey owner=root group=root mode=0600

- include: genconf_and_run.yml
  vars:
    corosync_transport: "udpu"

- include: genconf_and_run.yml
  vars:
    corosync_transport: "knet"

- name: stop corosync
  service: name=corosync state=stopped

