- name: remove old corosync.conf
  file: path=/etc/corosync/corosync.conf state=absent

- name: install corosync.conf {{ test_output }}
  template: src=corosync.conf.j2 dest=/etc/corosync/corosync.conf

- include: startcorosync.yml

- include: runtests.yml
