- include: hostupdate.yml
  when: skipupdate != 'yes'

- name: clean src/build dirs on demand
  file: path=/srv/knetansible/ state=absent
  when: wipecode == 'yes'

- name: create /srv/knetansible/src
  file: path=/srv/knetansible/src state=directory mode=0755

- name: create /srv/knetansible/build
  file: path=/srv/knetansible/build state=directory mode=0755
